#+TITLE: Projekt TDP028: \\ *Tekniskt PM*
#+AUTHOR: Jonas Vestlund
#+LATEX_CLASS_OPTIONS: [a4paper, 11pt]
#+LANGUAGE: sv
#+LATEX_HEADER: \usepackage[AUTO]{babel}
#+LATEX_HEADER: \usepackage{libertine}
#+LATEX_HEADER: \usepackage{unicode-math}
#+LATEX_HEADER: \setmathfont{TeX Gyre Pagella Math}
#+OPTIONS: toc:nil date:nil

* Introduktion

Mobilapplikationer har tagit världen med storm de senaste åren.  Med den stora
ökningen av användandet av smarta mobiltelefoner har mobilapplikationer blivit
en allt större marknad som både individuella utvecklare och företag - stora som
små - satsar mycket resurser på. Det här dokumentet ämnar att belysa några av de
aspekter som är viktiga att ha i åtanke vid utvecklingen av en mobilapplikation.

* Att designa för användaren
Det är viktigt att en mobilapplikation har en intuitiv och lätt hanterlig design
för att facilitera enkel användning för användaren. En storskalig studie visar
att den genomsnittliga användaren spenderar 59,23 minuter på sin telefon om
dagen \cite{time}.  Dock så används en applikation i genomsnitt endast 71,56
sekunder innan den stängs \cite{time}. Detta innebär att min applikation måste
vara väldigt snabb att komma igång och tillåta användaren att nyttja tjänsten
med så lite konfiguration som möjligt. Annars finns risken att användarna blir
irriterade, och söker sig till andra möjliga alternativ.


* Distribution och marknad
För en utvecklare har det aldrig varit enklare att komma igång med
applikationsutveckling. Företag som Google och Apple har satsat stora resurser
på att skapa centraliserade portaler för applikationer till deras enheter.  För
den enskilda utvecklaren innebär det här en enorm vinst i möjligheterna att nå
kunderna \cite{distribution}. För min egen del underlättar logistiken kring att
faktiskt distribuera väldigt mycket, men jag kan också använda det för att lättare
få användare att testa på det genom att de snabbt kan installera detta och testa
appen på egen hand.

* Viktiga attribut
Enligt en studie så är de viktigaste attributen av en mobilapplikationen i området
utbildning att den är attraktiv och träffsäker \cite{education}. Detta innebär
att jag måste designa en applikation med ett trevligt gränssnitt som användare
kan uppskatta. Hur träffsäker applikationens information är kan jag inte påverka,
då innehållet bestäms av kunden.


\begin{thebibliography}{1}

  \bibitem{distribution} Adrian Holzer, Jan Ondrus. Trends in Mobile Application Development.
  In {\em Volume 12 of the series Lecture Notes of the Institute for Computer Sciences, Social Informatics
and Telecommunications Engineering}, pages 55-64, Springer, Heidelberg, 2009.


  \bibitem{time} Matthias Böhmer, Brent Hecht, Johannes Schöning, Antonio Krüger, Gernot Bauer.
  Falling Asleep with Angry Birds, Facebook and Kindle - A Large Scale Study on Mobile Application Usage.
  In {\em Proceedings of the 13th International Conference on Human Computer Interaction with Mobile
  Devies and Services - MobileHCI 2011}, pages 46-56, New York, New York, USA, 2011. ACM Press.

  \bibitem{education} Bin Fu, Jialiu Lin, Lei Li, Christos Faloutsos, Jason Hong, Norman Sadeh.
  Why people hate your app: making sense of user feedback in a mobile app astore.
  In {\em Proceedings of the 19th ACM SIGKDD international conference on Knowledge discovery and data mining -
  KDD '13}, pages 1276-1284, New York, New York, USA, 2013. ACM Press.

  \end{thebibliography}
